### ISSUE TITLE
Tutorial file

### ISSUE THREAD

**Issue by PierreAndre24** [QUANTECA-QFox/prober_database#2]
https://github.com/QUANTECA-QFox/prober_database/blob/5619a704e98e517ec729f508b3788123c0863eee/prober_database/init/create_db.py#L1

This file belong to a tutorial section, not to the module directly

**Comment by lcontami** [comment]
Closing now that the tutorial file is created.
I would be enclined to leave this here so that it can be tested.
Repoen if you disagree
